language: python

python:
  - "3.5"

env:
  - TRAVIS_CL_TEST=1

install:
  - pip install -U setuptools
  - pip install -r requirements.txt
  - pip install anglerfish
  - pip install css-html-js-minify
  - pip install coveralls

script:
  - coverage run --source=landing,agcs runtests.py

after_success:
  - coveralls
