dist: trusty

sudo: required

language: python

addons:
  postgresql: "9.5"

services:
  - postgresql

python:
  - "3.5"

env:
  - TRAVIS_CL_TEST=1

install:
  - make install

before_script:
  - psql -c 'create database agcs_db;' -U postgres

script:
  - make travis

after_success:
  - codecov

branches:
  only:
    - master

