# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-30 10:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pubdocs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(upload_to=pubdocs.models.user_dir_path)),
                ('slug', models.SlugField(help_text='Unique identifier for this document', max_length=255, unique=True, verbose_name='slug')),
                ('info', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', related_query_name='doc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
    ]
