# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-30 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pubdocs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='doc',
            new_name='file',
        ),
    ]
