# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-07 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20170507_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Email Address'),
        ),
    ]
