# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='display_title',
            field=models.BooleanField(default=True),
        ),
    ]
