# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-29 05:03
from __future__ import unicode_literals

from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180328_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='tags',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
    ]
